config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  #
  root to: 'buddies#index'

  resources :buddies, only: [:new, :create, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :buddy

  validates :start_date, :end_date, :address, :buddy_id,
            presence: { message: "est obligatoire" }
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :first_name, :last_name, :skill, :price, :email, :address, :description, :image,
            presence: { message: "est obligatoire" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings.includes(:buddy)
    # @bookings = Booking.where(user_id: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @buddy = Buddy.find(params[:buddy_id])
  end

  def create
    @booking = Booking.new(params_booking)
    # #@buddy = Buddy.find(params[:buddy_id])
    @booking.buddy_id = params[:buddy_id]
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to bookings_path(@booking), notice: 'Buddy was successfully booked.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_booking
    params.require(:booking).permit(:start_date, :end_date, :address, :image)
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  before_action :set_buddies, only: :index
  def new
    @buddy = Buddy.new
  end

  def index
    @buddies = Buddy.all

    @buddies = @buddies.where(skill: params[:skill]) if params[:skill].present?

    @markers = @buddies.geocoded.map do |buddy|
      {
        lat: buddy.latitude,
        lng: buddy.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { buddy: buddy }),
        marker_html: render_to_string(partial: "marker", locals: { buddy: buddy })
      }
    end
  end

  def create
    @buddy = Buddy.new(buddy_params)
    @buddy.user = current_user
    if @buddy.save
      redirect_to root_path, notice: 'Buddy was successfully created.'
    else
      flash[:alert] = 'Buddy was not created !'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @buddy = Buddy.find(params[:id])
  end

  private

  def set_buddies
    @buddies_skill = params[:skill] ||= ""
    @buddies = params[:skill].present? ? Buddy.where(skill: params[:skill]) : Buddy.all
  end

  def buddy_params
    params.require(:buddy).permit(:first_name, :last_name, :email, :address, :skill, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="header">
<h2> My bookings</h1>
</div>
<div class="container-bookings mb-20">
  <div class="column">
    <% @bookings.each do |booking| %>
      <div class="booking-card col-12">
        <div class="card-header w-100 h-100 pb-5 pt-5">
          <div class="buddy-name">
            <%= "#{booking.buddy.first_name} #{booking.buddy.last_name}" %>
          </div>
          <div class="buddy-skill">
            <%= booking.buddy.skill %>
          </div>
        </div>
        <div class="card-image">
          <% if booking.buddy.image.attached? %>
            <%= image_tag booking.buddy.image, class: "image-booking-index", alt: "#{booking.buddy.first_name} #{booking.buddy.last_name}" %>
          <% else %>
            <%= image_tag "default_image.png", class: "image-booking-index", alt: "Default Image" %>
          <% end %>
        </div>
        <div class="card-dates">
          <p>
            <i class="fa fa-calendar-alt"></i>
            <strong>Start date:</strong> <%= booking.start_date.strftime("%d/%m/%Y") %></p>
          <p>
            <i class="fa fa-calendar-alt"></i>
            <strong>End date:</strong> <%= booking.end_date.strftime("%d/%m/%Y") %></p>
        </div>
        <div class="card-price">
          <p><strong>Price:</strong> <%= "#{booking.buddy.price}€" %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="header text-center">
<h2>Create a booking</h1>
</div>
<%= simple_form_for ([@buddy, @booking]) do |f|%>
<%= f.input :start_date, as: :date, html5: true, input_html:{class: 'input-box'}, label_html: {class: 'label-form'}  %>
<%= f.input :end_date, as: :date, html5: true, input_html:{class: 'input-box'}, label_html: {class: 'label-form'}  %>
<%= f.input :address, as: :string, input_html:{class: 'input-box'}, label_html: {class: 'label-form'}  %>
<div class="submit mb-3">
<%= f.button :submit, input_html: { class: 'submit' } %>
</div>
<% end %>

<div class="card-image">
  <% if @buddy.present? && @buddy.image.present? %>
    <%= image_tag @buddy.image, class: "image-booking-index", alt: "#{@buddy.first_name} #{@buddy.last_name}" %>
  <% else %>
    <%= image_tag "default_image.png", class: "image-booking-index", alt: "Default Image" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<header>

</header>

app/views/buddies/_info_window.html.erb
<h2><%= buddy.first_name %></h2>
<p><%= buddy.address %></p>

app/views/buddies/_marker.html.erb
<div class="badge rounded-pill bg-primary fs-6">
  <%= buddy.first_name %>
</div>

app/views/buddies/index.html.erb
<div class="big-container">
  <div class="container-index">
    <div class="search-bar">
    <%= render 'layouts/search_header' %>
    </div>


  <div class="buddies-card">
    <table>
      <tbody>
         <div class="map" style="width: 100%; height: 400px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
        <% @buddies.each do |buddy| %>
          <div class="card" style="width: 18rem;" id="card-buddy">
            <div class="card-buddy-image">
              <%= cl_image_tag buddy.image.key, height: 300, width: 300, crop: :fill, class: "card-img-top" %>
            </div>
            <div class="card-body">
              <div class="d-flex justify-content-between w-100">
                <h5 class="card-title"><%= buddy.first_name %></h5>
                <h5 class="card-skill"><%= buddy.skill %></h5>
              </div>
              <p class="card-text"><%= buddy.description %></p>
              <div class="btn-showw d-flex justify-content-end">
                <%= link_to 'Show', buddy_path(buddy), class: 'btn btn-show' %>
              </div>
              <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
      </div>
        <%= link_to 'Add a new Buddy', new_buddy_path, class: 'btn add-new-buddy-btn' %>
      </div>

</div>

app/views/buddies/new.html.erb
<div class="container mb-20">
  <div class="header text-center">
    <h2 class="text-blush">Create your buddy</h2>
  </div>

  <div class="flex justify-between items-center space-x-4">
    <div class="picture w-100 position-relative">
      <div class="position-absolute bottom-0 start-75">
        <i class="fa-solid fa-camera fs-4"></i>
      </div>
      <i class="fa-regular fa-user w-100"></i>

    </div>
  </div>
    <div class="form w-80" id="new_form_container">

      <%= render 'layouts/new_buddy_form' %>
    </div>
</div>
<%# test %>

app/views/buddies/show.html.erb
<header>
  <div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center position-relative">
      <!-- Bouton Retour à gauche -->
      <%= link_to root_path, class: "btn-back" do %>
        <i class="bi bi-arrow-left"></i> <!-- Utilisation d'une icône Bootstrap pour la flèche -->
      <% end %>

      <!-- Logo à droite -->
      <%= image_tag "logo.png", id: "logo", alt: "Logo de l'application", class: "logo-top-right" %>
    </div>
  </div>
</header>

</header>
<div class="container mt-4 mb-20">
  <h1 class="details-buddy mb-4">Détails du buddy</h1>

    <div class="card-body">
      <% if @buddy.image.attached? %>
    <div class="text-center mb-4">
          <!-- Image responsive -->
      <%= image_tag @buddy.image, class: "image-buddy-show", alt: "#{@buddy.first_name} #{@buddy.last_name}"%>
    </div>
    <% else %>
    <div class="text-center mb-4">
      <%= image_tag "default_image.png", class: "image-buddy-show", alt: "Default Buddy"%>
    </div>
    <% end %>

      <!-- Nom et Skill côte à côte -->
      <div class="container">
      <div class="d-flex justify-content-between align-items-center sm-3">
        <p class="buddy-name"><strong>Buddy Name:</strong> <%= @buddy.first_name %></p>
        <p class="buddy-skill"><strong>Skill:</strong> <%= @buddy.skill %></p>
      </div>
      </div>

  <div class="description-container mb-3">
    <p><strong>Description:</strong>
    <p><%= @buddy.description %></p>
  </div>
</div>

      <div class="d-flex justify-content-between align-items-center mt-4">
        <!-- Prix -->
        <p class="mb-0 fw-bold" style="font-size: 1.2rem; color: #333;">
          € <%= @buddy.price %>
        </p>


        <!-- Bouton "Book Your Buddy" -->
        <button class="link-button btn btn-pink text-white fw-bold py-2 px-4"
                style="background-color: #f48fb1; border: none; border-radius: 8px;">
          <%= link_to "Book your buddy", new_buddy_booking_path(@buddy)%>
        </button>
      </div>
    </div>
</div>

app/views/layouts/_buddy_card.html.erb
<!-- app/views/shared/_buddy_card.html.erb -->
<div class="bg-white p-4 mb-4 border-transparent rounded-lg shadow-sm">
  <div class="d-inline-flex items-center justify-between mb-2">
    <div class="d-inline-flex items-center space-x-3">
      <div class="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center">
        <i class="fas fa-user text-gray-400"></i>
      </div>
      <div>
        <h3 class="font-medium"><%= buddy.name %></h3>
        <p class="text-sm text-pink-500"><%= buddy.skill %></p>
      </div>
    </div>
    <div class="flex items-center">
      <span class="text-sm mr-1">4.3</span>
      <i class="fas fa-star text-green-500 text-sm"></i>
    </div>
  </div>

  <div class="flex justify-between items-center mt-2">
    <div class="flex items-center space-x-2">
      <i class="fas fa-euro-sign text-gray-600"></i>
      <span class="text-gray-600"><%= buddy.price %></span>
    </div>
    <div class="flex space-x-2">
      <a href="#" class="text-pink-500">
        <i class="fab fa-instagram"></i>
      </a>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <!-- Font Awesome CDN -->
  <%# <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"> %>


<!-- app/views/shared/_footer.html.erb -->
<div class="footer-big bg-dark-green rounded p-2 w-100 text-center">
  <footer class="bg-[#1E1E1E] fixed bottom-0 w-100">
    <div class="container w-100">
      <div class="flex justify-between items-center space-x-4">
        <a href="<%= root_path %>" class="text-pink-500">
          <i class="fas fa-search"></i>
        </a>
        <a href="#" class="text-pink-500">
          <i class="fas fa-heart"></i>
        </a>

        <a href="<%= bookings_path %>" class="text-pink-500">
          <i class="fas fa-calendar"></i>
        </a>
        <a href="#" class="text-pink-500">
          <i class="fas fa-user"></i>
        </a>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_new_buddy_form.html.erb
<div class="form-container w-75 text-center">
  <%= simple_form_for @buddy do |f| %>
    <%= f.input :image, label:false, input_html: { class: 'form-text'}, as: :file %>
    <%= f.input :first_name, label:false, placeholder: 'Put your First Name', input_html: { class: 'form-text'} %>
    <%= f.input :last_name, label:false, placeholder: 'Put your Last Name', input_html: { class: 'form-text'} %>
    <%= f.input :email, label:false, placeholder: 'Put your Email', input_html: { class: 'form-text'} %>
    <%= f.input :address, label:false, placeholder: 'Put your Address', input_html: { class: 'form-text'}  %>
    <%= f.input :skill, label:false, prompt: 'Choose your Skill', input_html: { class: 'form-text'}, collection: ["Chef", "DJ", "Hottie", "Clown", "Taxi", "Tattoo Artist", "Psy", "Web Dev", "Pub crawler"]%>
    <%= f.input :description, label:false, placeholder: 'Add a description', input_html: { class: 'form-text'} %>
    <%= f.input :price, label:false, placeholder: 'What is your price ?', input_html: { class: 'form-text'} %>
  <div class="submit">
      <%= f.button :submit, input_html: { class: 'submit' } %>
    </div>
  <% end %>
  </div>

app/views/layouts/_search_header.html.erb
<%# partial barre de recherche %>

<div class="text-center px-4 py-3 shadow-sm" id="search-bar">
  <div class="relative">
    <div class="absolute right-3 top-1/2 transform -translate-y-1/2">
      <%= form_with url: root_path, method: :get do |f| %>
        <%= f.select :skill, ["", "Chef", "DJ", "Hottie", "Clown", "Taxi", "Tattoo Artist", "Psy", "Web Dev", "Pub crawler"], selected: @buddies_skill %>
        <%= button_tag class: 'icon-look', type: 'submit' do %>
          <i class="fas fa-search text-pink-500" type="submit"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Le Bon Pote" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= favicon_link_tag asset_path('logo.png') %>
    <link rel="apple-touch-icon" href="/logo.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-3">
      <div class="row justify-content-center">
        <div class="col-12">
          <%= yield %>

          <% if notice %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <%= notice %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <% end %>

          <% if alert %>
            <div class="alert alert-dismissible fade show" role="alert">
              <%= alert %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <% end %>

          <%= render "layouts/footer" %>
        </div>
      </div>
    </div>
    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>